import Verbose.Tactics.Notations
import Verbose.Dutch.Assume
import Verbose.Dutch.By
import Verbose.Dutch.Calc
import Verbose.Dutch.Claim
import Verbose.Dutch.Fix
import Verbose.Dutch.Lets
import Verbose.Dutch.Since
import Verbose.Dutch.We
import Verbose.Dutch.Widget
import Verbose.Dutch.Statements
