import Verbose.Dutch.Assume
import Verbose.Dutch.By
import Verbose.Dutch.Since
import Verbose.Dutch.Claim
import Verbose.Dutch.Fix
import Verbose.Dutch.Lets
import Verbose.Dutch.Set
import Verbose.Dutch.We
import Verbose.Dutch.Calc
